import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Variable List
Typically, when someone refers to a "variable list" in Python, they mean a standard list object, created using square brackets. Python lists are dynamic, heterogeneous, and highly versatile.

Dynamic: Can grow or shrink in size.
Heterogeneous: Can store elements of different data types.
Versatile: Can hold any object type (integers, strings, objects, other lists, etc.).



In [1]:
variable_list = [1, "two", 3.0, [4, 5]]
print(variable_list)

[1, 'two', 3.0, [4, 5]]


Array List

In Python, an "array list" often refers to arrays provided by libraries such as array or numpy. These arrays are more specialized compared to Python's built-in lists.

Python array Module

Requires elements to be of the same type (homogeneous).

Offers more efficient storage for large collections of elements of the same type.

In [4]:
import numpy as np

l = ('i', [1, 2, 3, 4])  # Array of integers
ar = np.array(l)
ar


/tmp/ipykernel_70/1054634963.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar = np.array(l)


array(['i', list([1, 2, 3, 4])], dtype=object)

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [5]:
ar

array(['i', list([1, 2, 3, 4])], dtype=object)

In [28]:
print(ar.dtype)


object


In [20]:
variable_list

[1, 'two', 3.0, [4, 5]]

Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [32]:
num_list = [[1,2,3],[4,5,6]]
import numpy as np
num = np.array(num_list)

In [34]:
print(num.dtype)

int64


Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [35]:
import numpy as np

# Create a nested list
num_list = [[1, 2, 3], [4, 5, 6]]

# Convert the nested list to a NumPy array
num_array = np.array(num_list)

# Find the shape of the NumPy array
array_shape = num_array.shape

# Find the size of the NumPy array
array_size = num_array.size

# Print the shape and size
print("Shape of num_array:", array_shape)
print("Size of num_array:", array_size)


Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [36]:
import numpy as np

# Create a 3x3 matrix of zeros
zeros_matrix = np.zeros((3, 3))

# Print the zeros matrix
print(zeros_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [38]:
import numpy.matlib as nm


SyntaxError: invalid syntax (57888014.py, line 2)